[build]
  command = "cd frontend && canvas-sketch /src/weather-orbs.js --name index --build --inline && cd ../backend && npm run build:lambda && npm run start:lambda"
  functions = "./backend/serverless-functions/dist" #  netlify-lambda reads this
