#[build]
  #command = "canvas-sketch /src/weather-orbs.js --name index --build --inline && cd ../backend && npm run build:lambda"
  #functions = "../backend/serverless-functions/dist" #  netlify-lambda reads this
