[build]
  #command = "canvas-sketch ../src/weather-orbs.js --name index --build --dir public/ --inline && cd ../../backend && npm run build:lambda"
  functions = "./serverless-functions/dist" #  netlify-lambda reads this
